version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./cache-fe
      dockerfile: Dockerfile
    ports:
      - '1337:80'
    depends_on: 
      - 'backend'
  backend:
    container_name: backend
    build:
      context: ./cache-be
      dockerfile: Dockerfile 
    ports:
      - '8090:8080'      
    environment: 
      - CACHE_TABLE_NAME=cache_example
      - QUOTE_STORE_TABLE_NAME=cache_store_example
      - DAYS_TO_EXPIRE=30
      - AWS_REGION=eu-west-2
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - ENCRYPT_KEY=ahhhhhhhhhhhhhhhhhhhhhhhhh